import { createContext, useContext, useEffect, useMemo, useState, useCallback } from "react";

const LANG_KEY = "alphamatch.lang";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "zh", label: "简体中文" },
];

const DICT = {
  en: {
    "nav.howToPlay": "How to Play",
    "nav.faq": "FAQ",
    "nav.dashboard": "Dashboard",
    "nav.leaderboard": "Leaderboard",
    "nav.getStarted": "Get Started",
    "nav.connecting": "Connecting...",
    "nav.switchChain": "Switch Base Sepolia",
    "nav.language": "Language",
    "nav.contact": "Contact",
    "wallet.menu.wallet": "Wallet",
    "wallet.menu.copy": "Copy Address",
    "wallet.menu.copied": "Copied",
    "wallet.menu.profile": "Profile",
    "wallet.menu.disconnect": "Disconnect",
    "wallet.menu.close": "Close",
    "wallet.menu.address": "Address",
    "wallet.menu.balance": "Balance",
    "wallet.modal.kicker": "Wallet Access",
    "wallet.modal.title": "Connect Wallet",
    "wallet.modal.subtitle": "Choose an available wallet to enter AlphaMatch.",
    "wallet.modal.installed": "Installed",
    "wallet.modal.notInstalled": "Not Installed",
    "wallet.modal.connecting": "Connecting to wallet...",
    "wallet.modal.signing": "Waiting for signature...",
    "wallet.modal.available": "Ready to connect",
    "wallet.modal.connectAction": "Connect",
    "wallet.modal.installHint": "Install to continue",
    "wallet.modal.install": "Install",
    "wallet.modal.new": "New to Ethereum wallets?",
    "wallet.modal.learnMore": "Learn more",

    "landing.badge.live": "Live on Base",
    "landing.badge.tag": "BTC Direction Matching",
    "landing.hero.line1": "Bring Your Alpha.",
    "landing.hero.line2": "Let The Match",
    "landing.hero.line3": "Validate It On-Chain.",
    "landing.hero.desc":
      "Alpha is your independent market view. Match pairs it with peers in a 30-second BTC round, referenced against a shared oracle and recorded on-chain.",
    "landing.cta.primary": "Get Started",
    "landing.cta.secondary": "See How It Works",

    "landing.fact.0": "30-second rounds",
    "landing.fact.1": "1 USDC fixed entry",
    "landing.fact.2": "On-chain settlement",

    "landing.bridge.kicker": "Before You Enter",
    "landing.bridge.title": "Short BTC rounds. Shared oracle. Transparent outcomes.",
    "landing.bridge.desc":
      "Enter with conviction, match with real players, and settle against the same market reference every round.",
    "landing.bridge.chip.0": "1 USDC fixed entry",
    "landing.bridge.chip.1": "30s rounds",
    "landing.bridge.chip.2": "Peer-matched play",
    "landing.bridge.chip.3": "Claim to wallet",

    "landing.heroNote.label": "Alpha + Match",
    "landing.heroNote.text":
      "One independent view, tested against comparable participants through the same market reference.",

    "landing.stage.kicker": "Live Entry Format",
    "landing.stage.title": "Independent view in. Matched validation out.",
    "landing.stage.subtitle":
      "A short-form BTC round with fixed entry, transparent matching, and one oracle-driven outcome.",
    "landing.stage.summary.0": "1 USDC fixed stake",
    "landing.stage.summary.1": "Quick match or private room",
    "landing.stage.summary.2": "Direct wallet claims",

    "landing.strip.0": "Independent view, matched counterparties",
    "landing.strip.1": "USDC entry with flat 5% fee",
    "landing.strip.2": "One oracle for both sides",
    "landing.strip.3": "Non-custodial claims",
    "landing.strip.4": "Built for repeatable market view testing",

    "landing.why.kicker": "Why This Feels Different",
    "landing.why.title":
      "Same oracle, same clock, same rules — only your view differs.",
    "landing.why.desc":
      "AlphaMatch is built around short, structured rounds. You form a view, commit to a direction, and see the result resolve quickly through the same market reference for every participant.",
    "landing.story.0":
      "Form an independent BTC view, lock it on-chain, and know the result in under a minute.",
    "landing.story.1":
      "Choose quick peer matching or bring your own group into a private room with a clear round structure.",
    "landing.story.2":
      "Keep entry, oracle pricing, settlement, and claims visible on-chain from start to finish.",

    "landing.metric.exp.label": "Experience",
    "landing.metric.exp.value": "Live",
    "landing.metric.exp.note": "A round starts feeling real immediately.",
    "landing.metric.promise.label": "Core Promise",
    "landing.metric.promise.value": "Fair",
    "landing.metric.promise.note": "One market, one oracle, one result path.",

    "landing.product.kicker": "See The Product Loop",
    "landing.product.title": "The round logic should feel obvious in seconds.",
    "landing.product.preview": "Preview Flow",

    "landing.round.kicker": "Round Narrative",
    "landing.round.title": "Three moments. Zero ambiguity.",
    "landing.round.desc":
      "The product earns trust when the flow is intuitive, the stakes are visible, and the outcome is resolved without hidden intervention.",
    "landing.round.step": "Step",
    "landing.round.0.title": "Enter With Intent",
    "landing.round.0.desc":
      "Choose quick match for immediate peer matching, or open a private room and fill it with people whose market view you want to compare against.",
    "landing.round.1.title": "Lock A Conviction",
    "landing.round.1.desc":
      "You are not predicting some abstract market someday. You are calling BTC direction over the next 30 seconds and committing to it on-chain.",
    "landing.round.2.title": "See The Truth Land",
    "landing.round.2.desc":
      "One oracle, one settlement, one result. No house repricing, no operator discretion, no waiting around for a manual payout queue.",

    "landing.modes.kicker": "Ways To Play",
    "landing.modes.title": "Choose the matching format that fits the moment.",
    "landing.modes.desc":
      "Whether you want instant queueing, invite-only competition, or a softer first run, the product gives each player a clear way in.",
    "landing.modes.0.eyebrow": "Quick Match",
    "landing.modes.0.title": "Best when you want immediate peer matching.",
    "landing.modes.0.desc":
      "Join the queue, let the system fill the room, and take a fresh BTC view into a live round within seconds.",
    "landing.modes.0.detail": "Useful for repeatable signal testing and short-session play.",
    "landing.modes.1.eyebrow": "Private Arena",
    "landing.modes.1.title": "Best when you want a controlled comparison set.",
    "landing.modes.1.desc":
      "Create a shareable room code, choose the player count, and compare views inside a defined group with the same timing and payout rules.",
    "landing.modes.1.detail": "Well suited for communities, research groups, and friend circles.",
    "landing.modes.2.eyebrow": "Demo Friendly",
    "landing.modes.2.title": "Best when you want zero-pressure onboarding.",
    "landing.modes.2.desc":
      "New players can explore the flow before committing funds, making the first session feel approachable instead of risky.",
    "landing.modes.2.detail": "Useful for product demos, wallet onboarding, and first-time visitors.",

    "landing.edge.kicker": "The AlphaMatch Edge",
    "landing.edge.title": "Why AlphaMatch is more than a generic direction market.",
    "landing.edge.desc":
      "The strongest story is not just speed. It is speed combined with transparent rules, observable pricing, and peer-to-peer matching.",
    "landing.adv.0.title": "Peer vs Peer",
    "landing.adv.0.desc":
      "You are matched against real players with real positioning, not a bookmaker quietly pricing the other side.",
    "landing.adv.1.title": "Visible Payout Math",
    "landing.adv.1.desc":
      "Flat 5% fee, transparent prize logic, and no hidden spread between what you think you can win and what you actually receive.",
    "landing.adv.2.title": "Fast Enough For Repeatable Testing",
    "landing.adv.2.desc":
      "Short round loops help participants validate a market read quickly instead of waiting hours or days for feedback.",
    "landing.adv.3.title": "Built On Base",
    "landing.adv.3.desc":
      "Low-friction USDC play, EVM wallet support, and settlement on a chain users already recognize and trust.",
    "landing.adv.4.title": "Recovery By Design",
    "landing.adv.4.desc":
      "If a session breaks, the round state still exists on-chain. Players do not need to rely on support tickets to recover funds.",
    "landing.adv.5.title": "Made For Group Comparison",
    "landing.adv.5.desc":
      "Quick rounds and room codes make it easy to compare views with a group while keeping the rules, timing, and payout logic consistent.",

    "landing.faq.kicker": "FAQ",
    "landing.faq.title": "Everything serious players ask before round one.",
    "landing.faq.desc":
      "Payout, custody, fairness, and recovery are the details that turn curiosity into confidence.",
    "landing.faq.0.q": "What is AlphaMatch?",
    "landing.faq.0.a":
      "AlphaMatch is a real-time on-chain forecasting protocol on Base. Each round pairs two or more players who express an independent BTC market view over a 30-second window, with matching, locking, and settlement handled transparently on-chain.",
    "landing.faq.1.q": "Why the name AlphaMatch?",
    "landing.faq.1.a":
      "Alpha refers to your independent market judgment and differentiated view. Match refers to being paired with comparable participants in the same round so that your view can be tested against the market and against peers, not against a house.",
    "landing.faq.2.q": "How much does it cost to play?",
    "landing.faq.2.a":
      "Each prediction costs 1 USDC. A flat 5% platform fee is taken from the settled pool. There are no subscriptions, hidden spreads, or off-platform withdrawals.",
    "landing.faq.3.q": "How are winners decided?",
    "landing.faq.3.a":
      "When the round begins, the contract records the live BTC price as the opening reference. Thirty seconds later it reads the settlement price from the oracle, and players who called the right direction split the pool.",
    "landing.faq.4.q": "What is the payout?",
    "landing.faq.4.a":
      "Winners split the pool after a 5% fee. Bigger rooms and fewer winners mean higher upside; if everyone picks the same side, entries are refunded minus the fee. See the payout formula in the Dashboard for the exact calculation.",
    "landing.faq.5.q": "What wallet do I need?",
    "landing.faq.5.a":
      "Any EVM-compatible wallet works, including MetaMask, Coinbase Wallet, Rainbow, OKX, and Rabby. You only need USDC and a small amount of ETH on Base for gas.",
    "landing.faq.6.q": "Is it safe? Where are my funds?",
    "landing.faq.6.a":
      "Funds stay inside the smart-contract flow and settle directly to the players. AlphaMatch is non-custodial, so the platform never holds a pooled balance on your behalf.",
    "landing.faq.7.q": "What happens if I lose connection?",
    "landing.faq.7.a":
      "Every round has an on-chain recovery path. If settlement is interrupted or the oracle times out, you can still reclaim your entry or reward later from the result screen.",
    "landing.faq.8.q": "Can I create a private room with friends?",
    "landing.faq.8.a":
      "Yes. Choose Create Room, pick a team size from 2 to 5 players, and share the invite code. The arena starts automatically once every seat is filled and paid.",
    "landing.faq.9.q": "Which oracle does AlphaMatch use?",
    "landing.faq.9.a":
      "Rounds use a verifiable on-chain BTC/USD feed on Base for both the starting snapshot and the settlement read, so everyone plays from the same source of truth.",
    "landing.faq.10.q": "Is AlphaMatch gambling?",
    "landing.faq.10.a":
      "AlphaMatch is positioned as a skill-based peer-to-peer forecasting product. Users express a market view and are matched with other participants rather than a house counterparty. Outcomes are determined by observable price movement, not by randomness or dealer-set odds.",

    "landing.final.kicker": "Ready To Play",
    "landing.final.title": "Bring your market view. Let the next 30 seconds test it.",
    "landing.final.desc":
      "Connect a wallet, choose a matching format, and turn a short-term BTC view into a transparent on-chain result against real participants.",
    "landing.final.launch": "Launch App",
    "landing.final.review": "Review Gameplay",

    "landing.footer.howToPlay": "How to Play",
    "landing.footer.arena": "Arena",
    "landing.footer.rights": "© 2026 AlphaMatch. All rights reserved.",

    "login.badge": "SECURE CONNECT",
    "login.title": "Sign in to",
    "login.desc": "Connect your wallet to enter AlphaMatch and submit your first market view.",
    "login.connect": "Connect Wallet",
    "login.connecting": "Connecting...",
    "login.signing": "Waiting for signature...",
    "login.divider": "Non-custodial",
    "login.point1": "Your keys, your funds — always",
    "login.point2": "Works with MetaMask, Coinbase, OKX & more",
    "login.point3": "One signature to verify ownership — no gas",
    "login.foot": "By connecting, you agree to sign a verification message. No transaction, no gas.",
    "login.newHere": "New here?",
    "login.learn": "Learn how to play →",
    "login.back": "Back",

    "preview.step.join.title": "JOIN",
    "preview.step.join.desc": "5 players enter the arena",
    "preview.step.predict.title": "PREDICT",
    "preview.step.predict.desc": "Each player picks Long or Short",
    "preview.step.settle.title": "SETTLE",
    "preview.step.settle.desc": "30s countdown — BTC moves live",
    "preview.step.result.title": "RESULT",
    "preview.step.result.desc": "Winners split the pool instantly",
    "preview.lobby": "Arena Lobby",
    "preview.quickMatch": "⚡ Quick Match",
    "preview.quickMatch.desc": "Auto-matched instantly",
    "preview.roomCode": "🔑 Room Code",
    "preview.roomCode.desc": "Invite friends to play",
    "preview.rules": "Round Rules",
    "preview.rules.entry": "Entry",
    "preview.rules.duration": "Duration",
    "preview.rules.fee": "Fee",
    "preview.rules.max": "Max Players",
    "preview.long": "LONG",
    "preview.short": "SHORT",
    "preview.longTeam": "Long Team",
    "preview.shortTeam": "Short Team",
    "preview.longCount": "Long",
    "preview.shortCount": "Short",
    "preview.pool": "Pool",
    "preview.players": "Players",
    "preview.live": "Live",
    "preview.winner": "Long Wins — BTC Went Up",
    "preview.settled": "Settlement complete",
    "preview.onchain": "On-chain verified",
    "preview.hint.predict": "📌 Base price — locked when game starts, all players share the same price",
    "preview.hint.countdown": "⏱ Live price — 30s countdown, price moving in real-time",
    "preview.hint.result": "✅ Final price — compared with base price to determine winners",

    "arena.loading": "Loading...",
    "arena.title.logged": "Ready when you are.",
    "arena.title.guest": "Enter the arena.",
    "arena.subtitle": "Pick a matching format and lock your BTC direction for the next round.",
    "arena.balance": "USDC Balance",
    "arena.faucet": "Need test USDC?",
    "arena.faucet.link": "Get from faucet",
    "arena.mode.random.title": "Quick Match",
    "arena.mode.random.desc": "Jump into a live round with instant peer matching.",
    "arena.mode.random.cta": "Start Match",
    "arena.mode.create.title": "Create Room",
    "arena.mode.create.desc": "Open a private room, share code, fill seats.",
    "arena.mode.create.cta": "Create Room",
    "arena.mode.join.title": "Join Room",
    "arena.mode.join.desc": "Got a room code? Enter to play with friends.",
    "arena.mode.join.cta": "Join",
    "arena.history": "Recent Rounds",
    "arena.history.empty": "No rounds yet. Your next round will show up here.",
    "arena.history.win": "Win",
    "arena.history.lose": "Lose",
    "arena.history.refund": "Refund",
    "arena.history.pending": "Pending",
    "arena.viewResult": "View Result",

    "howto.title": "The Round, End To End",
    "howto.subtitle": "Short, structured BTC rounds. Your view, validated on-chain.",
    "howto.step1.title": "Connect & Fund",
    "howto.step1.desc": "Connect an EVM wallet and keep a little USDC on Base. No custody, no sign-up.",
    "howto.step2.title": "Join A Round",
    "howto.step2.desc": "Pick Quick Match for instant matching, or create a private room with a code.",
    "howto.step3.title": "Lock Direction",
    "howto.step3.desc": "Call BTC direction — Long or Short — for the next 30 seconds.",
    "howto.step4.title": "Settle & Claim",
    "howto.step4.desc": "One oracle, one settlement. Winners claim directly to their wallet.",
    "howto.rules": "House Rules",
    "howto.rule.0": "1 USDC fixed entry per round.",
    "howto.rule.1": "Flat 5% platform fee from the settled pool.",
    "howto.rule.2": "Room size: 2 to 5 players.",
    "howto.rule.3": "Round duration: 30 seconds, on-chain oracle settled.",
    "howto.rule.4": "Non-custodial — funds stay in the smart contract until payout.",
    "howto.cta": "Enter Arena",
    "howto.back": "← Back",
    "howto.subtitleDetail": "From wallet connection to on-chain settlement and direct claim, every AlphaMatch round follows the same transparent flow.",
    "howto.kicker": "Protocol Manual",
    "howto.meta.stake": "1 USDC · Fixed entry",
    "howto.meta.round": "30s · Prediction window",
    "howto.meta.onchain": "On-chain settlement",

    "howto.timeline.title": "Anatomy Of A Round",
    "howto.timeline.desc": "Every round follows the same four-phase rhythm — no hidden timers, no manual overrides.",
    "howto.timeline.0.label": "Match",
    "howto.timeline.0.time": "Before the round",
    "howto.timeline.0.desc": "Join Quick Match for instant pairing with other live participants, or open a private room with a share code.",
    "howto.timeline.1.label": "Submit",
    "howto.timeline.1.time": "0 – 25s",
    "howto.timeline.1.desc": "Record your directional view. Adjustable until lock; untouched after the window closes.",
    "howto.timeline.2.label": "Confirm",
    "howto.timeline.2.time": "25 – 30s",
    "howto.timeline.2.desc": "Views are frozen and posted to Base. The reserved five-second window guarantees inclusion before settlement begins.",
    "howto.timeline.3.label": "Settle",
    "howto.timeline.3.time": "30 – 60s",
    "howto.timeline.3.desc": "A fresh oracle-signed price is submitted on-chain. The contract compares base and settlement prices, then records the outcome.",
    "howto.timeline.4.label": "Claim",
    "howto.timeline.4.time": "After settlement",
    "howto.timeline.4.desc": "Participants on the correct side can withdraw their share directly to wallet \u2014 no queue, no approval.",

    "howto.stepsTitle": "Six Steps, End To End",
    "howto.stepsDesc": "A plain walk-through, from connecting a wallet to claiming rewards.",
    "howto.step.0.title": "Connect Wallet",
    "howto.step.0.desc": "Connect an EVM wallet, or start in demo mode with a virtual balance \u2014 no real funds required for practice rounds.",
    "howto.step.0.highlight": "Non-custodial from the first click",
    "howto.step.1.title": "Choose Your Format",
    "howto.step.1.desc": "Quick Match pairs you with live participants instantly. Create Arena opens a private room with an invite code for peer groups.",
    "howto.step.1.highlight": "Public pairing or invited peers",
    "howto.step.2.title": "Pay Entry",
    "howto.step.2.desc": "Each participant commits 1 USDC. The protocol retains a flat 5% fee (0.05 USDC); the remainder flows into the settlement pool.",
    "howto.step.2.highlight": "1 USDC stake \u00b7 5% protocol fee",
    "howto.step.3.title": "Record Direction",
    "howto.step.3.desc": "Within the 25-second submission window, record whether you expect BTC to move up or down. The final 5 seconds are reserved for on-chain confirmation, so submit early.",
    "howto.step.3.highlight": "Long or Short, within 25 seconds",
    "howto.step.4.title": "Await Settlement",
    "howto.step.4.desc": "Once views are locked, a 30-second settlement countdown runs. The final oracle-signed BTC price determines the outcome.",
    "howto.step.4.highlight": "Deterministic on-chain resolution",
    "howto.step.5.title": "Claim Reward",
    "howto.step.5.desc": "Participants on the correct side share the pool. If every view aligns, each participant simply receives their entry minus fee back, claimable on demand.",
    "howto.step.5.highlight": "Direct wallet withdrawal",

    "howto.modesTitle": "Two Ways To Participate",
    "howto.modesDesc": "Same rules, different audiences.",
    "howto.modes.quick.name": "Quick Match",
    "howto.modes.quick.desc": "Instant pairing with other live participants. Best for trying the format without planning ahead.",
    "howto.modes.quick.point0": "No coordination required",
    "howto.modes.quick.point1": "Room fills automatically to the current cap",
    "howto.modes.quick.point2": "Round begins the moment the room fills",
    "howto.modes.arena.name": "Create Arena",
    "howto.modes.arena.desc": "Open a private room with a one-time join code. Invited peers enter, and the round begins when the room is full.",
    "howto.modes.arena.point0": "Share a single join code",
    "howto.modes.arena.point1": "Choose room size between 2 and 5 participants",
    "howto.modes.arena.point2": "Ideal for structured peer groups",

    "howto.payoutTitle": "How Payout Is Calculated",
    "howto.payoutDesc": "A deterministic formula, executed by the settlement contract. There are no discretionary adjustments.",
    "howto.payoutFormula": "reward = entry \u00d7 (1 \u2212 fee) \u00d7 N / winnerCount",
    "howto.payoutLegend": "entry = 1 USDC \u00b7 fee = 5% \u00b7 N = room size \u00b7 winnerCount = participants on the correct side",
    "howto.payoutExamplesTitle": "Worked Examples",
    "howto.examples": "Payout Examples",
    "howto.example.0.title": "2 Participants \u00b7 Views Diverge",
    "howto.example.0.players": "A records Long \u2714 \u00b7 B records Short \u2718",
    "howto.example.0.result": "A receives \u2248 1.90 USDC \u00b7 B forfeits entry",
    "howto.example.1.title": "2 Participants \u00b7 Views Align",
    "howto.example.1.players": "Both record Long \u2714",
    "howto.example.1.result": "Each receives \u2248 0.95 USDC back (entry minus fee)",
    "howto.example.2.title": "5 Participants \u00b7 3 Correct / 2 Incorrect",
    "howto.example.2.players": "3 Long \u2714 \u00b7 2 Short \u2718",
    "howto.example.2.result": "Each correct participant \u2248 1.58 USDC",

    "howto.trustTitle": "Prices, Signatures, Transparency",
    "howto.trustDesc": "What the protocol relies on \u2014 and what you always control.",
    "howto.trust.oracle.label": "Price source",
    "howto.trust.oracle.body": "Settlement prices are streamed from Binance BTC/USDT spot (WebSocket primary, REST fallback), signed by an AlphaMatch oracle key, and posted on-chain. The settlement contract verifies the signature before the price is accepted.",
    "howto.trust.oracle.roadmapLabel": "Roadmap",
    "howto.trust.oracle.roadmap": "Currently using a team-operated signer oracle; planned migration to Chainlink Data Feeds.",
    "howto.trust.controlTitle": "What stays in your hands",
    "howto.trust.control.0.title": "Non-custodial",
    "howto.trust.control.0.desc": "Keys stay in your wallet. Funds enter the contract only for the duration of an active round.",
    "howto.trust.control.1.title": "No mid-round edits",
    "howto.trust.control.1.desc": "Once locked, neither participants nor the operator can modify recorded views.",
    "howto.trust.control.2.title": "On-chain evidence",
    "howto.trust.control.2.desc": "Every base price, settlement price, and payout is recorded on Base, independently auditable by any participant.",
    "howto.trust.control.3.title": "Direct claim",
    "howto.trust.control.3.desc": "Rewards are withdrawn by you, from you. No operator approval in between.",

    "howto.readyTitle": "Ready to take a round?",
    "howto.readyDesc": "Open the dashboard, pick a format, and let the protocol do the rest.",
    "howto.cta.primary": "Open Dashboard",
    "howto.cta.secondary": "Back to Home",

    "create.title": "Create Private Room",
    "create.subtitle": "Open a room, share the code, fill seats, start the round.",
    "create.size.label": "Room size",
    "create.size.hint": "2 to 5 players. Round starts once every seat pays.",
    "create.entry": "Entry per seat",
    "create.total": "Total pool",
    "create.cta.prepare": "Prepare Room",
    "create.cta.approving": "Approving USDC...",
    "create.cta.creating": "Creating on-chain...",
    "create.cta.confirm": "Confirm Payment",
    "create.cta.waiting": "Waiting for confirmation...",
    "create.code.label": "Room code",
    "create.code.copy": "Copy",
    "create.code.copied": "Copied",
    "create.share": "Share this code with friends",
    "create.seats": "Seats filled",
    "create.cancel": "Cancel Room",
    "create.status.waiting": "Waiting for players to join...",
    "create.status.ready": "Room full. Starting round...",
    "create.heading": "Create Arena",
    "create.teamSize": "Team size",
    "create.ctaCreate": "Create Arena",
    "create.arenaCode": "Arena Code",
    "create.copy.done": "✓ Copied",
    "create.copy.cta": "📋 Copy Code",
    "create.share.opponents": "Share this code with your opponents",
    "create.ready": "ready",
    "create.paid": "paid",
    "create.remaining": "remaining",
    "create.payment.countdown": "payment countdown",
    "create.cta.cancel": "Cancel",
    "create.creating": "Creating arena...",
    "create.cancelling": "Cancelling room...",
    "create.expired.msg": "Room expired — team not filled in time",
    "create.expired.cta": "Expired",
    "create.expired.redirect": "This room has already expired. Returning you to the dashboard...",
    "create.syncing": "Syncing on-chain confirmation...",
    "create.payment.timeout.title": "Payment Timed Out",
    "create.payment.full.title": "Pay to Start",
    "create.payment.action": "Pay 1 USDC",
    "create.payment.timeout.subtitle": "A player did not complete payment. This room has been dissolved.",
    "create.payment.full.subtitle": "All {n} players joined! Pay 1 USDC to start.",
    "create.payment.timeout.action": "Confirm",
    "create.err.teamDisbanded": "A player did not complete payment. This room has been dissolved.",
    "create.err.windowClosed": "Payment window closed",
    "create.err.paymentFailed": "Payment failed",
    "roomLobby.exit.confirm": "Confirm",
    "roomLobby.exit.expiredTitle": "Room Expired",
    "roomLobby.exit.expiredSubtitle": "This room expired before all seats were filled. Return to the dashboard to create or join another arena.",
    "roomLobby.exit.closedTitle": "Room Closed",
    "roomLobby.exit.closedSubtitle": "This room is no longer active. Return to the dashboard to continue.",

    "join.title": "Join A Room",
    "join.subtitle": "Paste the room code, pay the entry, play the round.",
    "join.code.label": "Room code",
    "join.code.placeholder": "e.g. A7F2",
    "join.cta.fetch": "Look Up Room",
    "join.cta.approving": "Approving USDC...",
    "join.cta.joining": "Joining on-chain...",
    "join.cta.confirm": "Confirm Payment",
    "join.cta.waiting": "Waiting for confirmation...",
    "join.room.info": "Room info",
    "join.room.size": "Seats",
    "join.room.entry": "Entry",
    "join.room.filled": "Filled",
    "join.not.found": "Room not found.",
    "join.full": "Room is full.",
    "join.heading": "Join Arena",
    "join.connectWallet": "Connect wallet first",
    "join.enterCode": "Enter room code",
    "join.codePlaceholder": "6-digit code",
    "join.ctaJoinMatch": "Join Match",
    "join.ctaJoin": "Join",
    "join.ctaCancel": "Cancel",
    "join.ctaLeave": "Leave",
    "join.confirm.title": "Join arena with code",
    "join.confirm.count": "{c}/{t} players in room",
    "join.joining": "Joining arena...",
    "join.joined": "Joined Arena",
    "join.waiting": "Waiting for opponents...",
    "join.remaining": "remaining",
    "join.payment.countdown": "payment countdown",
    "join.paid": "paid",
    "join.err.incompleteCode": "Enter complete 6-digit code",
    "join.err.expired": "Room expired — team not filled in time",
    "join.payment.full.title": "Pay to Start",
    "join.payment.timeout.title": "Payment Timed Out",
    "join.payment.action": "Pay 1 USDC",
    "join.payment.timeout.action": "Confirm",
    "join.payment.timeout.subtitle": "A player did not complete payment. This room has been dissolved.",
    "join.payment.full.subtitle": "All players joined! Pay 1 USDC to start.",

    "game.loading": "Loading round...",
    "game.phase.predict": "Predict",
    "game.phase.countdown": "Countdown",
    "game.phase.settling": "Settling",
    "game.phase.settled": "Settled",
    "game.pick.long": "LONG — BTC will go up",
    "game.pick.short": "SHORT — BTC will go down",
    "game.confirm": "Confirm Pick",
    "game.confirming": "Submitting on-chain...",
    "game.locked": "Your direction is locked.",
    "game.waiting": "Waiting for other players...",
    "game.base": "Base price",
    "game.current": "Live price",
    "game.timer": "Seconds left",
    "game.pool": "Pool",
    "game.longSide": "Long side",
    "game.shortSide": "Short side",
    "game.leave": "Leave Round",

    "result.loading": "Loading result...",
    "result.win": "You won",
    "result.lose": "Better luck next round",
    "result.refund": "Round refunded",
    "result.pending": "Settlement pending",
    "result.reward": "Reward",
    "result.entry": "Your entry",
    "result.claim": "Claim to wallet",
    "result.claiming": "Claiming...",
    "result.claimed": "Claimed",
    "result.refund.cta": "Refund",
    "result.refunding": "Refunding...",
    "result.refunded": "Refunded",
    "result.playAgain": "Play Continue",
    "result.back": "Back to Arena",
    "result.base": "Base",
    "result.settle": "Settle",
    "result.delta": "Change",
    "result.yourPick": "Your pick",
    "result.winners": "Winners",
    "result.losers": "Losers",
    "result.onchain": "On-chain verified",
    "result.matchNotFound": "Match not found",
    "result.matchNumber": "Match #",
    "result.settlement": "Settlement",

    "random.title": "Random Match",
    "random.teamSize": "Team size",
    "random.findMatch": "Find Match",
    "random.cancel": "Cancel",
    "random.preparing.note": "Players are locked in. Preparing the payment step now.",
    "random.payment.title.preparing": "Match Found",
    "random.payment.title.confirm": "Enter Match",
    "random.payment.subtitle.preparing": "All {n} players are ready. We're preparing the payment step now.",
    "random.payment.subtitle.confirm": "Pay entry fee to enter this match",
    "random.payment.action": "Pay 1 USDC",
    "random.payment.hint.preparing": "Creating the on-chain match now. This dialog will switch to `Pay 1 USDC` automatically as soon as setup finishes.",
    "random.payment.hint.mock": "Local mock payment enabled for this environment.",
    "random.payment.hint.confirm": "You'll confirm this payment in your wallet.",
    "random.err.noOpponents": "No opponents found. Try again.",
    "random.err.disconnect": "Connection lost during matchmaking. Please try again.",
    "random.err.paymentFailed": "Payment failed",

    "home.hero.title.pre": "Choose Your",
    "home.hero.title.highlight": "Match Format",
    "home.hero.desc": "Express your BTC market view, get matched with peers, and resolve the round on-chain in 30 seconds. Entry: {fee} USDC per round.",
    "home.demoBadge": "DEMO MODE · Virtual Balance · Zero Risk",
    "home.hint.connectWallet": "Connect wallet to join rounds",
    "home.hint.noWallet": "No wallet detected — demo mode available",
    "home.ticker.label": "BTC / USD Live",
    "home.ticker.live": "Live Market",
    "home.stats.wins": "Wins",
    "home.stats.losses": "Losses",
    "home.stats.profit": "Profit",
    "leaderboard.kicker": "Top Performers",
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Track the strongest wallets across private rooms and recent rounds. Rankings update from live player records on this environment.",
    "leaderboard.metric.players": "Listed Players",
    "leaderboard.metric.bestWinRate": "Best Win Rate",
    "leaderboard.metric.topProfit": "Top Profit",
    "leaderboard.you": "You",
    "leaderboard.top3": "Top 3",
    "leaderboard.loading": "Loading leaderboard...",
    "leaderboard.empty": "No ranked players yet.",
    "leaderboard.error": "Unable to load leaderboard right now.",
    "leaderboard.table.rank": "Rank",
    "leaderboard.table.player": "Player",
    "leaderboard.table.winRate": "Win Rate",
    "leaderboard.rankLabel": "Rank #{n}",
    "leaderboard.playerLabel": "Wallet",
    "home.card.create.title": "Create Room",
    "home.card.create.generated": "Generated room card",
    "home.card.create.desc": "Invite friends into the same match room",
    "home.card.create.generatedDesc": "Share this code to fill the room and trigger the payment step.",
    "home.countdown.expires": "Expires in",
    "home.countdown.payment": "Payment window",
    "home.card.join.title": "Join Room",
    "home.card.join.desc": "Enter a code to join the same match room",
    "home.card.match.title": "Quick Match",
    "home.card.match.desc": "Auto-match in 15 seconds",
    "home.teamSize": "Team Size",
    "home.payout.trigger": "Payout formula",
    "home.payout.heading": "Payout formula",
    "home.payout.formula": "reward = entry × (1 − fee) × N / winnerCount",
    "home.payout.legend": "entry = 1 USDC  ·  fee = 5%  ·  N = room size  ·  winnerCount = correct players",
    "home.payout.exampleLabel": "Example · 5 players · 1 correct · 4 wrong",
    "home.payout.exampleCalc": "1 × (1 − 5%) × 5 / 1 ≈ 4.75 USDC",
    "home.payout.exampleNote": "The single correct player receives the full pool after the 5% fee.",
    "home.payout.quickRules": "Payout formula",
    "home.payout.quickRulesNote": "Settlement logic executed on-chain by the arena contract.",
    "home.action.createArena": "Create Arena · {n}P",
    "home.action.findMatch": "Find Match · {n}P",
    "home.action.joinArena": "Join Arena",
    "home.arenaCode": "Arena Code",
    "home.joinedArena": "Joined Arena",
    "home.ready": "ready",
    "home.paid": "paid",
    "home.waiting": "waiting",
    "home.remaining": "remaining",
    "home.payment.countdown": "payment countdown",
    "home.preparingPayment": "Preparing payment...",
    "home.creating": "Creating room...",
    "home.cancelling": "Cancelling room...",
    "home.validating": "Validating code...",
    "home.joining": "Joining arena...",
    "home.copy.done": "✓ Copied",
    "home.copy.cta": "📋 Copy Code",
    "home.copy.clickHint": "Click to copy",
    "home.share.text": "I saved you a seat at AlphaMatch. Room code {code} → {url}",
    "home.share.twitter": "Share",
    "home.expiredMsg": "Room expired — team not filled in time",
    "home.expiredCta": "Expired",
    "home.preparingNote": "Players are locked in. Preparing the payment step now.",
    "home.cancel": "Cancel",
    "home.enterRoom": "Enter Room",
    "home.leave": "Leave",
    "home.join": "Join",
    "home.joinConfirm": "Join arena with code",
    "home.joinPlayersInRoom": "{n}/{total} players in room",
    "home.codePlaceholder": "6-digit code",
    "home.swipe.left": "← swipe",
    "home.swipe.right": "swipe →",
    "home.err.finishFirst": "Finish or cancel current action first",
    "home.err.alreadyCreating": "Already creating a room",
    "home.err.alreadyJoin": "Already in join flow",
    "home.err.alreadyMatching": "Already matching",
    "home.err.createBlocked.join": "Finish the current join flow before creating a room.",
    "home.err.createBlocked.match": "Finish the current match flow before creating a room.",
    "home.err.joinBlocked.create": "You already have an active room. Cancel or finish it before joining another one.",
    "home.err.joinBlocked.match": "Finish the current match flow before joining a room.",
    "home.err.matchBlocked.create": "You already have an active room. Cancel or finish it before starting a match.",
    "home.err.matchBlocked.join": "Finish the current join flow before starting a match.",
    "home.err.incompleteCode": "Enter complete 6-digit code",
    "home.err.invalidCode": "Invalid room code or server not responding",
    "home.err.serverUnavailable": "Server connection unavailable. Start the backend and try again.",
    "home.err.roomNotFound": "Room not found or expired",
    "home.err.noOpponents": "No opponents found. Try again.",
    "home.err.lostConn": "Connection lost during matchmaking. Please try again.",
    "home.err.missingGameId": "Missing game id",
    "home.err.paymentFailed": "Payment failed",
    "home.err.baseSlow": "Base Sepolia is taking longer than usual. Waiting for on-chain confirmation...",
    "home.err.timeoutTeam": "A player did not complete payment. This room has been dissolved.",
    "home.err.windowClosed": "Payment window closed",
    "home.history.title": "History",
    "home.history.filter.all": "All",
    "home.history.filter.create": "Create",
    "home.history.filter.join": "Join",
    "home.history.filter.random": "Random",
    "home.history.connect": "Connect wallet to view history",
    "home.history.empty": "No match history yet",
    "home.history.prev": "Prev",
    "home.history.next": "Next",
    "home.history.claim": "Claim",
    "home.history.claimed": "Claimed",
    "home.history.claiming": "Claiming...",
    "home.history.claimReward": "Claim Reward",
    "home.history.claimRefund": "Claim Refund",
    "home.history.refundReady": "Refund Ready",
    "home.history.refunded": "Refunded",
    "home.history.settled": "Settled",
    "home.history.waitingState": "Waiting",
    "home.history.playingState": "Playing",
    "home.history.expired": "Expired",
    "home.history.failed": "Failed",
    "home.history.cancelled": "Cancelled",
    "home.history.win": "Win",
    "home.history.lose": "Lose",
    "home.history.createRoom": "Create Room",
    "home.history.joinRoom": "Join Room",
    "home.history.randomMatch": "Random Match",
    "home.history.quick": "Quick",
    "home.history.room": "Room",
    "home.history.pending": "Pending",
    "home.history.awaiting": "Awaiting outcome",
    "home.history.emergencyRefund": "Emergency refund path unlocked",
    "home.history.settlementInterrupted": "Settlement interrupted",
    "home.quickRules": "Quick Rules",
    "home.learnMore": "Learn more →",
    "home.rule.entry": "{fee} USDC entry",
    "home.rule.predict": "30s to predict",
    "home.rule.settle": "30s settlement",
    "home.rule.pool": "Winning side shares pool",
    "home.recent.title": "Recent Matches",
    "home.recent.empty.title": "No matches yet",
    "home.recent.empty.desc": "Start a round to see your history",
    "home.footer": "Built on Base · USDC Settlements",
    "home.swipeLeft": "← swipe",
    "home.swipeRight": "swipe →",
    "home.payment.preparingTitle": "Preparing Payment",
    "home.payment.matchFoundTitle": "Match Found",
    "home.payment.confirmedTitle": "Payment Confirmed",
    "home.payment.roomFullTitle": "Pay to Start",
    "home.payment.enterMatchTitle": "Enter Match",
    "home.payment.timedOutTitle": "Payment Timed Out",
    "home.payment.timedOutSubtitle": "A player did not complete payment. This room has been dissolved.",
    "home.payment.cancelledTitle": "Payment Cancelled",
    "home.payment.cancelledSubtitle": "A player left the payment. Room closed and paid entries refunded.",
    "home.err.playerLeft": "A player left — room closed and paid entries refunded.",
    "home.err.hostLeft": "The host left — room closed and paid entries refunded.",
    "home.payment.waitingSubtitle": "Your entry is confirmed. Waiting for the remaining players to pay before the prediction begins automatically.",
    "home.payment.preparingRoomSubtitle": "All {n} players are ready. We're preparing the payment step now.",
    "home.payment.preparingMatchSubtitle": "All {n} players are ready. We're preparing the payment step now.",
    "home.payment.roomFullSubtitle": "All {n} players joined! Pay 1 USDC within {t}s to start the prediction.",
    "home.payment.enterMatchSubtitle": "Pay entry fee to enter this match",
    "home.payment.confirm": "Confirm",
    "result.confirm": "Confirm",
    "home.payment.action": "Pay 1 USDC",
    "home.payment.waitingHint": "You have already paid. The match will start as soon as all {n} players confirm.{mock}",
    "home.payment.mockAppend": " Local mock payment enabled.",
    "home.payment.preparingRoomHint": "Creating the on-chain game now. If this takes too long, the room will reset automatically.",
    "home.payment.preparingMatchHint": "Creating the on-chain match now. This dialog will switch to `Pay 1 USDC` automatically as soon as setup finishes.",
    "home.payment.roomFullHint.suffix": " · local mock payment enabled",
    "home.payment.mockHint": "Local mock payment enabled for this environment.",
    "home.payment.walletHint": "You'll confirm this payment in your wallet.",
    "home.payment.countdownLabel": "Match starts automatically once everyone pays before the timer expires.",

    "game.share.text": "Got a differentiated BTC view? Compare it on AlphaMatch. 📈📉 https://predict-arena-test.vercel.app/arena",
    "game.preparing.title": "Preparing Match",
    "game.preparing.desc": "Starting when all players are ready",
    "game.matchInProgress": "Match In Progress",
    "game.chooseSide": "Choose your side",
    "game.makePrediction": "Make your prediction",
    "game.turnPromptTitle": "Your turn: choose LONG or SHORT",
    "game.turnPromptHint": "Select LONG or SHORT in this panel to join the round.",
    "game.descLongShort": "Choose LONG if you think BTC will finish above the base price, or SHORT if you think it will finish below.",
    "game.timeLeft": "Time Left",
    "game.basePriceLabel": "Base Price",
    "game.livePriceLabel": "Live Price",
    "game.playersReady": "Players ready",
    "game.bufferNote": "Final {n}s are reserved locally for on-chain confirmation. Predictions are locked for this round.",
    "game.signingNote": "Confirm the signature in your wallet to lock this prediction for on-chain submission.",
    "game.yourPosition": "Your Position",
    "game.long": "LONG",
    "game.short": "SHORT",
    "game.noPos": "NO POSITION",
    "game.longArrow": "📈 LONG",
    "game.shortArrow": "📉 SHORT",
    "game.settling": "Settling...",
    "game.reveal": "Reveal",
    "game.viewingAs": "Viewing As",
    "game.role.host": "Host",
    "game.role.participant": "Participant",
    "game.role.viewer": "Viewer",
    "game.yourCall": "Your Call",
    "game.currentPrice": "Current Price",
    "game.interrupted.title": "Settlement Interrupted",
    "game.interrupted.desc": "Settlement was interrupted. Funds remain safe on-chain while recovery options load.",
    "game.chainGame": "Chain Game #",
    "game.recovery": "Recovery",
    "game.recovery.desc": "We keep checking the contract so you can claim the correct outcome from this page.",
    "game.recovery.reward": "On-Chain Reward",
    "game.recovery.loading": "Checking on-chain recovery status...",
    "game.recovery.reconnect": "Reconnect your wallet to see recovery options.",
    "game.recovery.unavailable": "Recovery status is temporarily unavailable. Refresh in a moment.",
    "game.recovery.alreadyClaimed": "Funds for this round have already been claimed to your wallet.",
    "game.recovery.rewardReady": "The round has already settled on-chain. You can claim your reward now.",
    "game.recovery.forceRefund": "The grace period has expired. We can unlock the emergency refund and claim it in one flow.",
    "game.recovery.refundReady": "Refund is ready on-chain. Confirm one transaction to return your entry fee.",
    "game.recovery.noClaim": "The round is settled on-chain, but this wallet has no claimable reward for this outcome.",
    "game.recovery.refundUnlock": "Settlement is still syncing. If the oracle does not finish first, the refund path unlocks in about {s}s.",
    "game.recovery.syncing": "Recovery is still syncing. You can also return to the home page and check history later.",
    "game.claim.reward": "Claim Reward",
    "game.claim.refund": "Claim Refund",
    "game.claiming": "Claiming...",
    "game.claimingReward": "Claiming Reward...",
    "game.rewardClaimed": "Reward Claimed",
    "game.rewardClaimSection": "Reward Claim",
    "game.rewardClaimDesc": "Winning funds are finalized on-chain after you confirm the claim transaction.",
    "game.claimable": "Claimable",
    "game.claimRefundWallet": "Refund claimed to wallet",
    "game.claimRewardWallet": "Reward claimed to wallet",
    "game.result.correct": "Forecast Confirmed",
    "game.result.wrong": "Forecast Missed",
    "game.result.youPredicted": "You predicted",
    "game.result.rewardReady": "Your reward is ready on-chain. Claim it to return funds to your wallet.",
    "game.result.noReward": "This round has no claimable reward for your wallet.",
    "game.endModal.winTitle": "You Won",
    "game.endModal.loseTitle": "Game Over",
    "game.endModal.winKicker": "Round Won",
    "game.endModal.loseKicker": "Round Complete",
    "game.endModal.winBody": "Profit secured for this round.",
    "game.endModal.loseBody": "This game has ended. Return to the dashboard to start another round.",
    "game.endModal.profit": "Profit",
    "game.endModal.settled": "Settled Direction",
    "game.home": "Home",
    "game.arena": "Arena",
    "game.shareX": "Share to 𝕏",
    "game.err.settlementInterrupted": "Settlement was interrupted. Funds remain safe on-chain.",
    "game.err.predictionFailed": "Prediction failed. Please try again.",
    "game.err.claimFailed": "Claim failed. Please try again.",
    "game.err.cannotRestore": "We couldn't restore this match yet. Give it a moment or return home.",
    "game.err.gameError": "Game error",
    "game.err.notInGame": "Not in this game",
  },
  zh: {
    "nav.howToPlay": "玩法介绍",
    "nav.faq": "FAQ",
    "nav.dashboard": "控制台",
    "nav.leaderboard": "排行榜",
    "nav.getStarted": "立即开始",
    "nav.connecting": "连接中...",
    "nav.switchChain": "切换到 Base Sepolia",
    "nav.language": "Language",
    "nav.contact": "联系我们",
    "wallet.menu.wallet": "钱包",
    "wallet.menu.copy": "复制地址",
    "wallet.menu.copied": "已复制",
    "wallet.menu.profile": "Profile",
    "wallet.menu.disconnect": "断开连接",
    "wallet.menu.close": "关闭",
    "wallet.menu.address": "地址",
    "wallet.menu.balance": "余额",
    "wallet.modal.kicker": "钱包接入",
    "wallet.modal.title": "连接钱包",
    "wallet.modal.subtitle": "选择一个可用钱包，继续进入 AlphaMatch。",
    "wallet.modal.installed": "已安装",
    "wallet.modal.notInstalled": "未安装",
    "wallet.modal.connecting": "正在连接钱包...",
    "wallet.modal.signing": "等待钱包签名...",
    "wallet.modal.available": "可直接连接",
    "wallet.modal.connectAction": "连接",
    "wallet.modal.installHint": "安装后继续",
    "wallet.modal.install": "安装",
    "wallet.modal.new": "第一次使用以太坊钱包？",
    "wallet.modal.learnMore": "了解更多",

    "landing.badge.live": "BASE 主网运行中",
    "landing.badge.tag": "BTC 方向预测",
    "landing.hero.line1": "亮出你的判断。",
    "landing.hero.line2": "让接下来的一局,",
    "landing.hero.line3": "在链上为你验证。",
    "landing.hero.desc":
      "Alpha 是你独立的市场观点,Match 让它与其他参与者在同一场 30 秒 BTC 行情中参照同一预言机,链上透明记录。",
    "landing.cta.primary": "立即开始",
    "landing.cta.secondary": "了解玩法",

    "landing.fact.0": "30 秒一轮",
    "landing.fact.1": "固定 1 USDC 入场",
    "landing.fact.2": "链上结算",

    "landing.bridge.kicker": "进入之前",
    "landing.bridge.title": "短时 BTC 对局，共用预言机，结果透明结算。",
    "landing.bridge.desc":
      "带着判断入场，与真实玩家匹配，并在每一局中基于同一市场基准完成结算。",
    "landing.bridge.chip.0": "固定 1 USDC 入场",
    "landing.bridge.chip.1": "30 秒一轮",
    "landing.bridge.chip.2": "真人匹配对局",
    "landing.bridge.chip.3": "直达钱包领取",

    "landing.heroNote.label": "Alpha + Match",
    "landing.heroNote.text": "一份独立判断,与同场其他参与者基于同一市场基准进行对照。",

    "landing.stage.kicker": "实时对局规则",
    "landing.stage.title": "亮出判断,链上完成结算。",
    "landing.stage.subtitle": "短时 BTC 对局,固定入场,透明撮合,单一预言机结算。",
    "landing.stage.summary.0": "固定 1 USDC 入场",
    "landing.stage.summary.1": "快速匹配 / 私人房间",
    "landing.stage.summary.2": "直达钱包领取",

    "landing.strip.0": "独立判断,真实参与者",
    "landing.strip.1": "USDC 入场,固定 5% 平台费",
    "landing.strip.2": "双方共用一个预言机",
    "landing.strip.3": "非托管领取",
    "landing.strip.4": "可复盘的市场观点检验",

    "landing.why.kicker": "AlphaMatch 的不同之处",
    "landing.why.title": "同一个预言机、同一个时钟、同一套规则 —— 只有你的判断是变量。",
    "landing.why.desc":
      "AlphaMatch 围绕短时、结构化的对局打造。你形成判断、选择方向,并基于同一市场基准快速见证结果。",
    "landing.story.0": "形成独立 BTC 判断,链上锁定,一分钟内见结果。",
    "landing.story.1": "支持快速匹配,也可邀好友进入私人房间,规则清晰一致。",
    "landing.story.2": "入场、预言机取价、结算、领取全流程链上可见。",

    "landing.metric.exp.label": "体验",
    "landing.metric.exp.value": "即时",
    "landing.metric.exp.note": "对局从开始就是真实的。",
    "landing.metric.promise.label": "核心承诺",
    "landing.metric.promise.value": "公平",
    "landing.metric.promise.note": "同一市场、同一预言机、同一结算路径。",

    "landing.product.kicker": "看见产品闭环",
    "landing.product.title": "对局流程应该几秒钟内一目了然。",
    "landing.product.preview": "流程预览",

    "landing.round.kicker": "对局流程",
    "landing.round.title": "三个节点,没有模糊地带。",
    "landing.round.desc": "流程直观、入场明确、结果无人工干预,产品才能真正被信任。",
    "landing.round.step": "第",
    "landing.round.0.title": "带着意图入场",
    "landing.round.0.desc":
      "选择快速匹配立即配对,或创建私人房间,邀请你想比对观点的人加入。",
    "landing.round.1.title": "锁定一个判断",
    "landing.round.1.desc":
      "你不是在预测遥远的未来,而是在链上锁定接下来 30 秒的 BTC 方向。",
    "landing.round.2.title": "见证真相落地",
    "landing.round.2.desc": "一个预言机、一次结算、一个结果。无重定价、无人工干预、无排队领取。",

    "landing.modes.kicker": "多种玩法",
    "landing.modes.title": "选择最符合当下的对局形式。",
    "landing.modes.desc": "无论是即刻排队、私人房间,还是轻松体验,每位玩家都有清晰入口。",
    "landing.modes.0.eyebrow": "快速匹配",
    "landing.modes.0.title": "适合即刻想要真人同场的场景。",
    "landing.modes.0.desc": "加入队列,系统自动配对,数秒内进入实时对局。",
    "landing.modes.0.detail": "适合短局反复检验市场判断。",
    "landing.modes.1.eyebrow": "私人房间",
    "landing.modes.1.title": "适合想要受控比对群体的场景。",
    "landing.modes.1.desc":
      "创建可分享的房间码,自选人数,在固定规则下与指定群组同台比对观点。",
    "landing.modes.1.detail": "适用于社群、研究小组与好友圈。",
    "landing.modes.2.eyebrow": "新手友好",
    "landing.modes.2.title": "适合零压力的首次体验。",
    "landing.modes.2.desc": "先熟悉流程再投入资金,让第一次游玩不显风险。",
    "landing.modes.2.detail": "适合产品演示、钱包引导与新访客。",

    "landing.edge.kicker": "AlphaMatch 的特点",
    "landing.edge.title": "AlphaMatch 与一般方向市场的差异。",
    "landing.edge.desc": "关键不只是速度,而是速度 + 透明规则 + 可观察报价 + 真人参与。",
    "landing.adv.0.title": "真人同场",
    "landing.adv.0.desc": "同场的是有真实入场的其他玩家,不是默默定价的做市方。",
    "landing.adv.1.title": "可见的赔付逻辑",
    "landing.adv.1.desc": "统一 5% 平台费,奖金逻辑透明,无隐藏价差。",
    "landing.adv.2.title": "足够快的反复验证",
    "landing.adv.2.desc": "短局循环,让玩家几秒内验证判断,无需等数小时或数天。",
    "landing.adv.3.title": "构建在 Base 上",
    "landing.adv.3.desc": "低门槛 USDC 玩法,支持 EVM 钱包,在用户熟悉信赖的链上结算。",
    "landing.adv.4.title": "容错设计",
    "landing.adv.4.desc": "对局数据链上保留,流程中断也能自行领回入场金或奖励,无需人工工单。",
    "landing.adv.5.title": "为群体比对而生",
    "landing.adv.5.desc": "短局 + 房间码,让一群人基于一致规则同步比对判断。",

    "landing.faq.kicker": "常见问题",
    "landing.faq.title": "严肃玩家在第一局前想问的一切。",
    "landing.faq.desc": "赔付、托管、公平性、容错 —— 这些细节把好奇变成信心。",
    "landing.faq.0.q": "AlphaMatch 是什么?",
    "landing.faq.0.a":
      "AlphaMatch 是一套部署在 Base 上的实时链上预测协议。每一局将两名以上玩家在 30 秒的窗口内配对,让每个人表达独立的 BTC 判断,匹配、锁定、结算全部链上透明完成。",
    "landing.faq.1.q": "为什么叫 AlphaMatch?",
    "landing.faq.1.a":
      "Alpha 代表你独立的市场判断和差异化观点,Match 代表在同一场次中与可比玩家配对,让你的判断与市场和同场参与者进行对照,而不是面对做市方。",
    "landing.faq.2.q": "玩一局需要多少钱?",
    "landing.faq.2.a":
      "每次预测 1 USDC。平台从结算奖池抽取统一 5% 手续费。没有订阅费、隐藏价差,也没有场外提现。",
    "landing.faq.3.q": "结果如何判定?",
    "landing.faq.3.a":
      "对局开始时,合约记录当下 BTC 价作为起始基准。30 秒后从预言机读取结算价,方向判断正确的玩家瓜分奖池。",
    "landing.faq.4.q": "奖金大概多少?",
    "landing.faq.4.a":
      "方向正确的玩家在扣除 5% 手续费后按比例瓜分奖池;房间人数越多、正确人数越少,单人潜在收益越高。若全员方向一致,则退回扣除手续费后的入场金。具体公式可查看 Dashboard 的奖金说明。",
    "landing.faq.5.q": "需要什么钱包?",
    "landing.faq.5.a":
      "任何兼容 EVM 的钱包都行,例如 MetaMask、Coinbase Wallet、Rainbow、OKX、Rabby。你只需要 Base 网络上的 USDC 与少量 ETH(用于 Gas)。",
    "landing.faq.6.q": "资金安全吗?放在哪里?",
    "landing.faq.6.a":
      "资金始终在智能合约流程内,结算后直达玩家。AlphaMatch 非托管,平台不代持任何资金池。",
    "landing.faq.7.q": "掉线会怎样?",
    "landing.faq.7.a":
      "每局都有链上容错路径。如果结算中断或预言机超时,你依然可以稍后通过结果页面领回入场金或奖励。",
    "landing.faq.8.q": "能和朋友一起开私人房间吗?",
    "landing.faq.8.a":
      "可以。选择创建房间,设置 2-5 人,分享邀请码即可。所有席位就绪并付款后自动开始。",
    "landing.faq.9.q": "AlphaMatch 用的是哪个预言机?",
    "landing.faq.9.a":
      "对局使用 Base 上可验证的链上 BTC/USD 喂价,作为起始与结算的统一参考,所有人共用同一事实源。",
    "landing.faq.10.q": "AlphaMatch 是赌博吗?",
    "landing.faq.10.a":
      "AlphaMatch 定位为一款基于技能的点对点预测产品。玩家表达市场判断,并与其他真实玩家配对,而非面对做市方。结果由可观察的价格变动决定,不涉及随机数或人为设定赔率。",

    "landing.final.kicker": "准备开始",
    "landing.final.title": "带上你的判断,让接下来的 30 秒为它做检验。",
    "landing.final.desc":
      "连接钱包,选择匹配形式,把一次短期 BTC 观点,变成链上透明、与真实参与者对照的结果。",
    "landing.final.launch": "启动应用",
    "landing.final.review": "回顾玩法",

    "landing.footer.howToPlay": "玩法介绍",
    "landing.footer.arena": "竞技场",
    "landing.footer.rights": "© 2026 AlphaMatch. All rights reserved.",

    "login.badge": "安全连接",
    "login.title": "登录",
    "login.desc": "连接钱包,进入 AlphaMatch,提交你的第一个市场判断。",
    "login.connect": "连接钱包",
    "login.connecting": "连接中...",
    "login.signing": "等待签名...",
    "login.divider": "非托管",
    "login.point1": "你的私钥,永远由你掌控",
    "login.point2": "支持 MetaMask、Coinbase、OKX 等主流钱包",
    "login.point3": "一次签名验证所有权 — 无需支付 Gas",
    "login.foot": "连接即表示你同意签署一条验证消息。无交易,无 Gas。",
    "login.newHere": "第一次来?",
    "login.learn": "了解玩法 →",
    "login.back": "返回",

    "preview.step.join.title": "加入",
    "preview.step.join.desc": "5 位玩家进入竞技场",
    "preview.step.predict.title": "预测",
    "preview.step.predict.desc": "每位玩家选择做多或做空",
    "preview.step.settle.title": "结算",
    "preview.step.settle.desc": "30 秒倒计时 — BTC 实时波动",
    "preview.step.result.title": "结果",
    "preview.step.result.desc": "获胜者即刻瓜分奖池",
    "preview.lobby": "竞技场大厅",
    "preview.quickMatch": "⚡ 快速匹配",
    "preview.quickMatch.desc": "即时自动配对",
    "preview.roomCode": "🔑 房间码",
    "preview.roomCode.desc": "邀请好友一起玩",
    "preview.rules": "对局规则",
    "preview.rules.entry": "入场",
    "preview.rules.duration": "时长",
    "preview.rules.fee": "手续费",
    "preview.rules.max": "最多人数",
    "preview.long": "做多",
    "preview.short": "做空",
    "preview.longTeam": "做多队",
    "preview.shortTeam": "做空队",
    "preview.longCount": "做多",
    "preview.shortCount": "做空",
    "preview.pool": "奖池",
    "preview.players": "对阵",
    "preview.live": "实时",
    "preview.winner": "做多方向正确 — BTC 上涨",
    "preview.settled": "结算完成",
    "preview.onchain": "链上已验证",
    "preview.hint.predict": "📌 基准价 — 开局时锁定,所有玩家共用同一价格",
    "preview.hint.countdown": "⏱ 实时价 — 30 秒倒计时,价格实时波动",
    "preview.hint.result": "✅ 结算价 — 与基准价比对,得出结果",

    "arena.loading": "加载中...",
    "arena.title.logged": "准备就绪,随时开始。",
    "arena.title.guest": "进入竞技场。",
    "arena.subtitle": "选择匹配形式,锁定下一局的 BTC 方向。",
    "arena.balance": "USDC 余额",
    "arena.faucet": "需要测试 USDC?",
    "arena.faucet.link": "前往水龙头领取",
    "arena.mode.random.title": "快速匹配",
    "arena.mode.random.desc": "即刻配对,立即进入实时对局。",
    "arena.mode.random.cta": "开始匹配",
    "arena.mode.create.title": "创建房间",
    "arena.mode.create.desc": "开一个私人房间,分享房间码,等席位坐满。",
    "arena.mode.create.cta": "创建房间",
    "arena.mode.join.title": "加入房间",
    "arena.mode.join.desc": "有房间码? 输入即可和朋友一起开局。",
    "arena.mode.join.cta": "加入",
    "arena.history": "最近记录",
    "arena.history.empty": "还没有对局。下一局结果会出现在这里。",
    "arena.history.win": "胜",
    "arena.history.lose": "负",
    "arena.history.refund": "退款",
    "arena.history.pending": "待结算",
    "arena.viewResult": "查看结果",

    "howto.title": "AlphaMatch 玩法",
    "howto.subtitle": "短时、结构化的 BTC 对局。你的判断,链上验证。",
    "howto.step1.title": "连接与充值",
    "howto.step1.desc": "连接 EVM 钱包,在 Base 上备一点 USDC。非托管,无需注册。",
    "howto.step2.title": "加入对局",
    "howto.step2.desc": "选择快速匹配即刻配对,或用房间码开私人房间。",
    "howto.step3.title": "锁定方向",
    "howto.step3.desc": "在 30 秒内选择 BTC 方向 —— 做多或做空。",
    "howto.step4.title": "结算与领取",
    "howto.step4.desc": "一个预言机,一次结算。获胜者直接领至钱包。",
    "howto.rules": "基本规则",
    "howto.rule.0": "每局固定 1 USDC 入场。",
    "howto.rule.1": "从奖池统一抽取 5% 平台费。",
    "howto.rule.2": "房间人数: 2 至 5 人。",
    "howto.rule.3": "单局时长: 30 秒,链上预言机结算。",
    "howto.rule.4": "非托管 — 资金在派发前始终留在智能合约中。",
    "howto.cta": "进入竞技场",
    "howto.back": "← 返回",
    "howto.subtitleDetail": "带上你独立的市场观点,AlphaMatch 通过六个透明步骤完成配对、记录与结算。",
    "howto.kicker": "协议说明",
    "howto.meta.stake": "1 USDC · 固定入场",
    "howto.meta.round": "30 秒 · 预测窗口",
    "howto.meta.onchain": "链上结算",

    "howto.timeline.title": "一局的完整节奏",
    "howto.timeline.desc": "每一局都遵循相同的四个阶段 —— 没有隐藏计时,也没有人工干预。",
    "howto.timeline.0.label": "匹配",
    "howto.timeline.0.time": "开局前",
    "howto.timeline.0.desc": "选择快速匹配与其他在线用户即刻配对,或用房间码开启私人房间。",
    "howto.timeline.1.label": "提交",
    "howto.timeline.1.time": "0 – 25 秒",
    "howto.timeline.1.desc": "记录你的方向判断。锁定前可调整,窗口关闭后不再变动。",
    "howto.timeline.2.label": "确认",
    "howto.timeline.2.time": "25 – 30 秒",
    "howto.timeline.2.desc": "观点冻结并提交至 Base 链,预留的 5 秒窗口确保在结算开始前被打包。",
    "howto.timeline.3.label": "结算",
    "howto.timeline.3.time": "30 – 60 秒",
    "howto.timeline.3.desc": "新的预言机签名价格提交上链。合约对比起始价与结算价,判定并记录结果。",
    "howto.timeline.4.label": "领取",
    "howto.timeline.4.time": "结算后",
    "howto.timeline.4.desc": "方向正确的用户可将奖金直接领至钱包 —— 无排队,无人工审批。",

    "howto.stepsTitle": "六步完整流程",
    "howto.stepsDesc": "从连接钱包到领取奖励的逐步说明。",
    "howto.step.0.title": "连接钱包",
    "howto.step.0.desc": "连接 EVM 钱包,或使用带虚拟余额的演示模式 —— 练习对局无需真实资金。",
    "howto.step.0.highlight": "从第一步起即为非托管",
    "howto.step.1.title": "选择参与方式",
    "howto.step.1.desc": "快速匹配即刻与在线用户配对;创建房间可用邀请码开启私密房间,适合小范围讨论。",
    "howto.step.1.highlight": "公开配对或邀请加入",
    "howto.step.2.title": "支付入场",
    "howto.step.2.desc": "每位用户提交 1 USDC。协议收取 5% 固定费用(0.05 USDC),其余进入结算池。",
    "howto.step.2.highlight": "1 USDC 入场 · 5% 协议费",
    "howto.step.3.title": "记录方向",
    "howto.step.3.desc": "在 25 秒提交窗口内记录 BTC 涨跌判断。最后 5 秒用于链上确认,请尽早提交。",
    "howto.step.3.highlight": "25 秒内提交做多或做空",
    "howto.step.4.title": "等待结算",
    "howto.step.4.desc": "观点锁定后进入 30 秒结算倒计时。合约根据预言机签名的最终价格判定结果。",
    "howto.step.4.highlight": "合约确定性结算",
    "howto.step.5.title": "领取奖金",
    "howto.step.5.desc": "方向正确的用户共享奖池。若全场方向一致,所有用户按入场金减手续费退回,可随时领至钱包。",
    "howto.step.5.highlight": "奖金直接进入钱包",

    "howto.modesTitle": "两种参与方式",
    "howto.modesDesc": "规则相同,面向不同场景。",
    "howto.modes.quick.name": "快速匹配",
    "howto.modes.quick.desc": "与其他在线用户即刻配对。最适合不想预先协调的首次体验。",
    "howto.modes.quick.point0": "无需协调",
    "howto.modes.quick.point1": "按当前房间上限自动匹配",
    "howto.modes.quick.point2": "满员即刻开始本局",
    "howto.modes.arena.name": "创建房间",
    "howto.modes.arena.desc": "用邀请码开启私人房间,成员入场后满员自动开始。",
    "howto.modes.arena.point0": "分享一次性加入码",
    "howto.modes.arena.point1": "房间人数 2–5 人可选",
    "howto.modes.arena.point2": "适合有讨论场景的小群体",

    "howto.payoutTitle": "奖金如何计算",
    "howto.payoutDesc": "由结算合约执行的确定性公式,不存在任何人工调整。",
    "howto.payoutFormula": "reward = entry × (1 − fee) × N / winnerCount",
    "howto.payoutLegend": "entry = 1 USDC · fee = 5% · N = 房间人数 · winnerCount = 方向正确的人数",
    "howto.payoutExamplesTitle": "三个实例",
    "howto.examples": "赔付示例",
    "howto.example.0.title": "2 人 · 观点分歧",
    "howto.example.0.players": "A 记录做多 ✔ · B 记录做空 ✘",
    "howto.example.0.result": "A 获得约 1.90 USDC · B 失去入场金",
    "howto.example.1.title": "2 人 · 观点一致",
    "howto.example.1.players": "双方均记录做多 ✔",
    "howto.example.1.result": "各自获得约 0.95 USDC(入场金扣手续费)",
    "howto.example.2.title": "5 人 · 3 方向正确 / 2 方向错误",
    "howto.example.2.players": "3 人做多 ✔ · 2 人做空 ✘",
    "howto.example.2.result": "方向正确者各得约 1.58 USDC",

    "howto.trustTitle": "价格来源、签名、可验证性",
    "howto.trustDesc": "协议依赖什么,以及你始终掌握什么。",
    "howto.trust.oracle.label": "价格来源",
    "howto.trust.oracle.body": "结算价格来自 Binance BTC/USDT 现货(WebSocket 实时订阅 + REST 轮询兜底),由 AlphaMatch 预言机私钥签名后提交至合约,合约完成验签才会采信。",
    "howto.trust.oracle.roadmapLabel": "路线图",
    "howto.trust.oracle.roadmap": "当前使用团队运营的签名预言机,计划迁移至 Chainlink Data Feeds。",
    "howto.trust.controlTitle": "始终由你掌握的部分",
    "howto.trust.control.0.title": "非托管",
    "howto.trust.control.0.desc": "私钥保留在你的钱包;资金仅在本局活动期间进入合约。",
    "howto.trust.control.1.title": "中途不可修改",
    "howto.trust.control.1.desc": "观点一旦锁定,任何成员和平台都无法修改已记录的内容。",
    "howto.trust.control.2.title": "全程链上可查",
    "howto.trust.control.2.desc": "每一次起始价、结算价与奖金流转都记录在 Base 链,任何人都能独立核对。",
    "howto.trust.control.3.title": "自主领取",
    "howto.trust.control.3.desc": "奖金由你自己提取,全程无平台审批。",

    "howto.readyTitle": "准备好开始?",
    "howto.readyDesc": "打开 Dashboard,选择一种方式,剩下交给协议。",
    "howto.cta.primary": "进入 Dashboard",
    "howto.cta.secondary": "返回首页",

    "create.title": "创建私人房间",
    "create.subtitle": "开一个房间,分享房间码,等席位坐满后开始。",
    "create.size.label": "房间人数",
    "create.size.hint": "2-5 人。所有席位付款后自动开局。",
    "create.entry": "每人入场",
    "create.total": "总奖池",
    "create.cta.prepare": "准备房间",
    "create.cta.approving": "USDC 授权中...",
    "create.cta.creating": "链上创建中...",
    "create.cta.confirm": "确认支付",
    "create.cta.waiting": "等待确认中...",
    "create.code.label": "房间码",
    "create.code.copy": "复制",
    "create.code.copied": "已复制",
    "create.share": "把房间码分享给朋友",
    "create.seats": "已就位",
    "create.cancel": "取消房间",
    "create.status.waiting": "等待玩家加入...",
    "create.status.ready": "房间已满,进入对局...",
    "create.heading": "创建竞技场",
    "create.teamSize": "房间人数",
    "create.ctaCreate": "创建竞技场",
    "create.arenaCode": "房间码",
    "create.copy.done": "✓ 已复制",
    "create.copy.cta": "📋 复制房间码",
    "create.share.opponents": "把房间码分享给你的好友",
    "create.ready": "就位",
    "create.paid": "已支付",
    "create.remaining": "剩余",
    "create.payment.countdown": "支付倒计时",
    "create.cta.cancel": "取消",
    "create.creating": "创建中...",
    "create.cancelling": "取消房间中...",
    "create.expired.msg": "房间已过期 — 人数未在时限内集齐",
    "create.expired.cta": "已过期",
    "create.expired.redirect": "该房间已过期，正在返回控制台...",
    "create.syncing": "同步链上确认中...",
    "create.payment.timeout.title": "支付超时",
    "create.payment.full.title": "支付后开始",
    "create.payment.action": "支付 1 USDC",
    "create.payment.timeout.subtitle": "存在用户未支付，房间已解散。",
    "create.payment.full.subtitle": "{n} 位玩家已加入,支付 1 USDC 即可开始。",
    "create.payment.timeout.action": "确认",
    "create.err.teamDisbanded": "存在用户未支付，房间已解散。",
    "create.err.windowClosed": "支付窗口已关闭",
    "create.err.paymentFailed": "支付失败",
    "roomLobby.exit.confirm": "确认",
    "roomLobby.exit.expiredTitle": "房间已过期",
    "roomLobby.exit.expiredSubtitle": "该房间未在时限内集齐人数，现已失效。返回控制台后可重新创建或加入其他房间。",
    "roomLobby.exit.closedTitle": "房间已关闭",
    "roomLobby.exit.closedSubtitle": "该房间当前已不可用。返回控制台后可继续操作。",

    "join.title": "加入房间",
    "join.subtitle": "粘贴房间码,支付入场费,进入对局。",
    "join.code.label": "房间码",
    "join.code.placeholder": "例如 A7F2",
    "join.cta.fetch": "查询房间",
    "join.cta.approving": "USDC 授权中...",
    "join.cta.joining": "链上加入中...",
    "join.cta.confirm": "确认支付",
    "join.cta.waiting": "等待确认中...",
    "join.room.info": "房间信息",
    "join.room.size": "人数",
    "join.room.entry": "入场",
    "join.room.filled": "已就位",
    "join.not.found": "未找到该房间。",
    "join.full": "房间已满。",
    "join.heading": "加入竞技场",
    "join.connectWallet": "请先连接钱包",
    "join.enterCode": "输入房间码",
    "join.codePlaceholder": "6 位房间码",
    "join.ctaJoinMatch": "加入对局",
    "join.ctaJoin": "加入",
    "join.ctaCancel": "取消",
    "join.ctaLeave": "离开",
    "join.confirm.title": "使用房间码加入",
    "join.confirm.count": "房间内 {c}/{t} 位玩家",
    "join.joining": "加入中...",
    "join.joined": "已加入",
    "join.waiting": "等待其他玩家...",
    "join.remaining": "剩余",
    "join.payment.countdown": "支付倒计时",
    "join.paid": "已支付",
    "join.err.incompleteCode": "请输入完整的 6 位房间码",
    "join.err.expired": "房间已过期 — 人数未在时限内集齐",
    "join.payment.full.title": "支付后开始",
    "join.payment.timeout.title": "支付超时",
    "join.payment.action": "支付 1 USDC",
    "join.payment.timeout.action": "确认",
    "join.payment.timeout.subtitle": "存在用户未支付，房间已解散。",
    "join.payment.full.subtitle": "玩家已全部加入,支付 1 USDC 即可开始。",

    "game.loading": "对局加载中...",
    "game.phase.predict": "预测阶段",
    "game.phase.countdown": "倒计时",
    "game.phase.settling": "结算中",
    "game.phase.settled": "已结算",
    "game.pick.long": "做多 — 看涨 BTC",
    "game.pick.short": "做空 — 看跌 BTC",
    "game.confirm": "确认选择",
    "game.confirming": "链上提交中...",
    "game.locked": "方向已锁定。",
    "game.waiting": "等待其他玩家...",
    "game.base": "基准价",
    "game.current": "实时价",
    "game.timer": "剩余秒数",
    "game.pool": "奖池",
    "game.longSide": "做多方",
    "game.shortSide": "做空方",
    "game.leave": "离开对局",

    "result.loading": "结果加载中...",
    "result.win": "你赢了",
    "result.lose": "下一局再见",
    "result.refund": "本局退款",
    "result.pending": "结算中",
    "result.reward": "奖励",
    "result.entry": "你的入场",
    "result.claim": "领取到钱包",
    "result.claiming": "领取中...",
    "result.claimed": "已领取",
    "result.refund.cta": "退款",
    "result.refunding": "退款中...",
    "result.refunded": "已退款",
    "result.playAgain": "继续游戏",
    "result.back": "返回竞技场",
    "result.base": "基准",
    "result.settle": "结算",
    "result.delta": "涨跌",
    "result.yourPick": "你的方向",
    "result.winners": "胜方",
    "result.losers": "败方",
    "result.onchain": "链上已验证",
    "result.matchNotFound": "未找到对局",
    "result.matchNumber": "对局 #",
    "result.settlement": "结算价",

    "random.title": "随机匹配",
    "random.teamSize": "房间人数",
    "random.findMatch": "开始匹配",
    "random.cancel": "取消",
    "random.preparing.note": "玩家已锁定。正在准备支付步骤。",
    "random.payment.title.preparing": "已完成配对",
    "random.payment.title.confirm": "进入对局",
    "random.payment.subtitle.preparing": "{n} 位玩家已就位,正在准备支付步骤。",
    "random.payment.subtitle.confirm": "支付入场费以进入本局",
    "random.payment.action": "支付 1 USDC",
    "random.payment.hint.preparing": "正在链上创建对局。准备完成后此弹窗会自动切换为 `支付 1 USDC`。",
    "random.payment.hint.mock": "当前环境启用本地模拟支付。",
    "random.payment.hint.confirm": "请在钱包中确认本次支付。",
    "random.err.noOpponents": "未找到其他玩家,请再试一次。",
    "random.err.disconnect": "匹配中连接中断,请重试。",
    "random.err.paymentFailed": "支付失败",

    "home.hero.title.pre": "选择你的",
    "home.hero.title.highlight": "对局形式",
    "home.hero.desc": "表达你的 BTC 市场判断,与其他玩家配对,30 秒内在链上完成结算。每局入场费 {fee} USDC。",
    "home.demoBadge": "演示模式 · 虚拟余额 · 零风险",
    "home.hint.connectWallet": "连接钱包即可进入对局",
    "home.hint.noWallet": "未检测到钱包 — 可使用演示模式",
    "home.ticker.label": "BTC / USD 实时价",
    "home.ticker.live": "实时行情",
    "home.stats.wins": "胜",
    "home.stats.losses": "负",
    "home.stats.profit": "盈亏",
    "leaderboard.kicker": "顶尖玩家",
    "leaderboard.title": "排行榜",
    "leaderboard.subtitle": "查看当前环境里表现最强的钱包地址。排行基于真实玩家胜负和收益数据实时更新。",
    "leaderboard.metric.players": "上榜玩家",
    "leaderboard.metric.bestWinRate": "最高胜率",
    "leaderboard.metric.topProfit": "最高盈利",
    "leaderboard.you": "你",
    "leaderboard.top3": "前三名",
    "leaderboard.loading": "排行榜加载中...",
    "leaderboard.empty": "暂时还没有排行数据。",
    "leaderboard.error": "当前无法加载排行榜。",
    "leaderboard.table.rank": "排名",
    "leaderboard.table.player": "玩家",
    "leaderboard.table.winRate": "胜率",
    "leaderboard.rankLabel": "第 {n} 名",
    "leaderboard.playerLabel": "钱包",
    "home.card.create.title": "创建房间",
    "home.card.create.generated": "已生成房间卡",
    "home.card.create.desc": "邀请好友进入同一房间",
    "home.card.create.generatedDesc": "分享这个房间码，房间满员后就会进入支付步骤。",
    "home.countdown.expires": "剩余时间",
    "home.countdown.payment": "支付倒计时",
    "home.card.join.title": "加入房间",
    "home.card.join.desc": "输入房间码,进入同场对局",
    "home.card.match.title": "快速匹配",
    "home.card.match.desc": "15 秒内自动配对",
    "home.teamSize": "房间人数",
    "home.payout.trigger": "奖金公式",
    "home.payout.heading": "奖金计算公式",
    "home.payout.formula": "reward = entry × (1 − fee) × N / winnerCount",
    "home.payout.legend": "entry = 1 USDC  ·  fee = 5%  ·  N = 房间人数  ·  winnerCount = 方向正确人数",
    "home.payout.exampleLabel": "示例 · 5 人房间 · 1 人正确 · 4 人错误",
    "home.payout.exampleCalc": "1 × (1 − 5%) × 5 / 1 ≈ 4.75 USDC",
    "home.payout.exampleNote": "唯一方向正确的玩家,独得扣除手续费后的全部奖池。",
    "home.payout.quickRules": "奖金计算公式",
    "home.payout.quickRulesNote": "结算由竞技场合约在链上执行,结果可公开核验。",
    "home.action.createArena": "创建竞技场 · {n}人",
    "home.action.findMatch": "开始匹配 · {n}人",
    "home.action.joinArena": "加入竞技场",
    "home.arenaCode": "房间码",
    "home.joinedArena": "已加入",
    "home.ready": "就位",
    "home.paid": "已支付",
    "home.waiting": "等待中",
    "home.remaining": "剩余",
    "home.payment.countdown": "支付倒计时",
    "home.preparingPayment": "准备支付中...",
    "home.creating": "正在创建房间...",
    "home.cancelling": "取消房间中...",
    "home.validating": "验证房间码中...",
    "home.joining": "加入中...",
    "home.copy.done": "✓ 已复制",
    "home.copy.cta": "📋 复制房间码",
    "home.copy.clickHint": "点击复制",
    "home.share.text": "我在 AlphaMatch 留了个位置给你。房间码 {code} → {url}",
    "home.share.twitter": "分享",
    "home.expiredMsg": "房间已过期 — 人数未在时限内集齐",
    "home.expiredCta": "已过期",
    "home.preparingNote": "玩家已锁定,正在准备支付步骤。",
    "home.cancel": "取消",
    "home.enterRoom": "进入房间",
    "home.leave": "离开",
    "home.join": "加入",
    "home.joinConfirm": "使用房间码加入对局",
    "home.joinPlayersInRoom": "房间内 {n}/{total} 位玩家",
    "home.codePlaceholder": "6 位房间码",
    "home.swipe.left": "← 左滑",
    "home.swipe.right": "右滑 →",
    "home.err.finishFirst": "请先完成或取消当前操作",
    "home.err.alreadyCreating": "已有正在创建的房间",
    "home.err.alreadyJoin": "已在加入流程中",
    "home.err.alreadyMatching": "已在匹配中",
    "home.err.createBlocked.join": "请先完成当前加入流程，再创建房间。",
    "home.err.createBlocked.match": "请先完成当前匹配流程，再创建房间。",
    "home.err.joinBlocked.create": "已有活跃房间,请先取消或完成后再加入其它房间。",
    "home.err.joinBlocked.match": "请先完成当前匹配流程再加入房间。",
    "home.err.matchBlocked.create": "已有活跃房间,请先取消或完成后再开始匹配。",
    "home.err.matchBlocked.join": "请先完成当前加入流程，再开始匹配。",
    "home.err.incompleteCode": "请输入完整的 6 位房间码",
    "home.err.invalidCode": "房间码无效或服务器未响应",
    "home.err.serverUnavailable": "服务器连接不可用，请启动后端后重试。",
    "home.err.roomNotFound": "房间不存在或已过期",
    "home.err.noOpponents": "未找到其他玩家,请再试一次。",
    "home.err.lostConn": "匹配中连接中断,请重试。",
    "home.err.missingGameId": "缺少对局 ID",
    "home.err.paymentFailed": "支付失败",
    "home.err.baseSlow": "Base Sepolia 响应较慢,正在等待链上确认...",
    "home.err.timeoutTeam": "有玩家未在规定时间内完成支付，房间已解散。",
    "home.err.windowClosed": "支付窗口已关闭",
    "home.err.rpcTimeout": "Base Sepolia RPC 在等待确认时超时,请稍后重试。",
    "home.err.paymentNotConfirmed": "支付已发送,但服务器仍在同步确认,请稍候。",
    "home.err.configStale": "支付配置已过期,请刷新页面后重试。",
    "home.err.allowancePending": "授权已完成,但支付交易尚未就绪,请稍后再试。",
    "home.err.roomSyncing": "房间支付仍在链上同步,请稍后重试。",
    "home.history.title": "历史记录",
    "home.history.filter.all": "全部",
    "home.history.filter.create": "创建",
    "home.history.filter.join": "加入",
    "home.history.filter.random": "随机",
    "home.history.connect": "连接钱包查看历史",
    "home.history.empty": "暂无对局记录",
    "home.history.prev": "上一页",
    "home.history.next": "下一页",
    "home.history.claim": "领取",
    "home.history.claimed": "已领取",
    "home.history.claiming": "领取中...",
    "home.history.claimReward": "领取奖励",
    "home.history.claimRefund": "领取退款",
    "home.history.refundReady": "可退款",
    "home.history.refunded": "已退款",
    "home.history.settled": "已结算",
    "home.history.waitingState": "等待中",
    "home.history.playingState": "进行中",
    "home.history.expired": "已过期",
    "home.history.failed": "失败",
    "home.history.cancelled": "已取消",
    "home.history.win": "胜",
    "home.history.lose": "负",
    "home.history.createRoom": "创建房间",
    "home.history.joinRoom": "加入房间",
    "home.history.randomMatch": "随机匹配",
    "home.history.quick": "快速",
    "home.history.room": "房间",
    "home.history.pending": "待结算",
    "home.history.awaiting": "等待结果",
    "home.history.emergencyRefund": "可申请紧急退款",
    "home.history.settlementInterrupted": "结算中断",
    "home.quickRules": "快速规则",
    "home.learnMore": "了解更多 →",
    "home.rule.entry": "{fee} USDC 入场",
    "home.rule.predict": "30 秒预测",
    "home.rule.settle": "30 秒结算",
    "home.rule.pool": "获胜方瓜分奖池",
    "home.recent.title": "最近对局",
    "home.recent.empty.title": "还没有对局",
    "home.recent.empty.desc": "开始一局后,历史会显示在这里",
    "home.footer": "构建在 Base 上 · USDC 结算",
    "home.swipeLeft": "← 左滑",
    "home.swipeRight": "右滑 →",
    "home.payment.preparingTitle": "准备支付",
    "home.payment.matchFoundTitle": "已完成配对",
    "home.payment.confirmedTitle": "支付已确认",
    "home.payment.roomFullTitle": "支付后开始",
    "home.payment.enterMatchTitle": "进入对局",
    "home.payment.timedOutTitle": "支付超时",
    "home.payment.timedOutSubtitle": "因未所有玩家按时完成支付,房间已关闭。",
    "home.payment.cancelledTitle": "支付已取消",
    "home.payment.cancelledSubtitle": "有玩家退出了本次支付,房间已关闭,已支付的入场费已退款。",
    "home.err.playerLeft": "有玩家退出 — 房间已关闭,已支付的入场费已退款。",
    "home.err.hostLeft": "房主退出 — 房间已关闭,已支付的入场费已退款。",
    "home.payment.waitingSubtitle": "你的入场已确认。等待其余玩家完成支付后,对局将自动开始。",
    "home.payment.preparingRoomSubtitle": "{n} 位玩家已就位,正在准备支付步骤。",
    "home.payment.preparingMatchSubtitle": "{n} 位玩家已就位,正在准备支付步骤。",
    "home.payment.roomFullSubtitle": "{n} 位玩家已加入,请在 {t} 秒内支付 1 USDC 开始预测。",
    "home.payment.enterMatchSubtitle": "支付入场费以进入本局",
    "home.payment.confirm": "确认",
    "result.confirm": "确认",
    "home.payment.action": "支付 1 USDC",
    "home.payment.waitingHint": "你已完成支付。{n} 位玩家全部确认后对局将自动开始。{mock}",
    "home.payment.mockAppend": " 本地模拟支付已启用。",
    "home.payment.preparingRoomHint": "正在链上创建对局。若等待时间过长,房间会自动重置。",
    "home.payment.preparingMatchHint": "正在链上创建对局,准备就绪后此弹窗会自动切换为 `支付 1 USDC`。",
    "home.payment.roomFullHint.suffix": " · 已启用本地模拟支付",
    "home.payment.mockHint": "当前环境启用本地模拟支付。",
    "home.payment.walletHint": "请在钱包中确认本次支付。",
    "home.payment.countdownLabel": "所有玩家在计时结束前完成支付后,对局将自动开始。",

    "game.share.text": "有不一样的 BTC 判断? 来 AlphaMatch 对照一下。 📈📉 https://predict-arena-test.vercel.app/arena",
    "game.preparing.title": "准备对局",
    "game.preparing.desc": "玩家全部就绪后开始",
    "game.matchInProgress": "对局进行中",
    "game.chooseSide": "选择你的方向",
    "game.makePrediction": "做出你的预测",
    "game.turnPromptTitle": "轮到你了：选择做多或做空",
    "game.turnPromptHint": "请在此区域选择做多或做空，加入本轮预测。",
    "game.descLongShort": "如果你认为 BTC 会高于基准价,选择做多;认为会低于,选择做空。",
    "game.timeLeft": "剩余时间",
    "game.basePriceLabel": "基准价",
    "game.livePriceLabel": "实时价",
    "game.playersReady": "已就位玩家",
    "game.bufferNote": "最后 {n} 秒用于链上确认,本局不再接受新预测。",
    "game.signingNote": "请在钱包中确认签名以锁定本次链上预测。",
    "game.yourPosition": "你的方向",
    "game.long": "做多",
    "game.short": "做空",
    "game.noPos": "未选",
    "game.longArrow": "📈 做多",
    "game.shortArrow": "📉 做空",
    "game.settling": "结算中...",
    "game.reveal": "揭晓",
    "game.viewingAs": "观战身份",
    "game.role.host": "房主",
    "game.role.participant": "玩家",
    "game.role.viewer": "观战",
    "game.yourCall": "你的选择",
    "game.currentPrice": "当前价",
    "game.interrupted.title": "结算已中断",
    "game.interrupted.desc": "结算过程中断,资金仍安全保存在链上,正在加载恢复选项。",
    "game.chainGame": "链上对局 #",
    "game.recovery": "恢复",
    "game.recovery.desc": "我们会持续读取合约,让你在本页领取正确的结算结果。",
    "game.recovery.reward": "链上奖励",
    "game.recovery.loading": "查询链上恢复状态中...",
    "game.recovery.reconnect": "请重新连接钱包以查看恢复选项。",
    "game.recovery.unavailable": "恢复状态暂不可用,请稍后刷新。",
    "game.recovery.alreadyClaimed": "本局资金已领取到你的钱包。",
    "game.recovery.rewardReady": "对局已在链上结算,现在可以领取奖励。",
    "game.recovery.forceRefund": "宽限期已过,可一次性解锁并领取紧急退款。",
    "game.recovery.refundReady": "退款已在链上就绪,确认一笔交易即可退回入场金。",
    "game.recovery.noClaim": "对局已在链上结算,但此钱包在本局没有可领取的奖励。",
    "game.recovery.refundUnlock": "结算仍在同步。若预言机未先完成,退款路径约 {s} 秒后解锁。",
    "game.recovery.syncing": "恢复仍在同步,你也可以先返回首页稍后再从历史查看。",
    "game.claim.reward": "领取奖励",
    "game.claim.refund": "领取退款",
    "game.claiming": "领取中...",
    "game.claimingReward": "奖励领取中...",
    "game.rewardClaimed": "奖励已领取",
    "game.rewardClaimSection": "领取奖励",
    "game.rewardClaimDesc": "在你确认领取交易后,获胜资金将在链上最终确认。",
    "game.claimable": "可领取",
    "game.claimRefundWallet": "退款已领至钱包",
    "game.claimRewardWallet": "奖励已领至钱包",
    "game.result.correct": "判断正确",
    "game.result.wrong": "判断错误",
    "game.result.youPredicted": "你预测的是",
    "game.result.rewardReady": "奖励已在链上就绪,领取即可返回到你的钱包。",
    "game.result.noReward": "本局你的钱包没有可领取奖励。",
    "game.endModal.winTitle": "你赢了",
    "game.endModal.loseTitle": "游戏结束",
    "game.endModal.winKicker": "本局获胜",
    "game.endModal.loseKicker": "本局结束",
    "game.endModal.winBody": "本局盈利已确认。",
    "game.endModal.loseBody": "本局游戏已经结束，可返回控制台再开一局。",
    "game.endModal.profit": "盈利",
    "game.endModal.settled": "结果方向",
    "game.home": "首页",
    "game.arena": "竞技场",
    "game.shareX": "分享到 𝕏",
    "game.err.settlementInterrupted": "结算中断,资金仍安全保留在链上。",
    "game.err.predictionFailed": "预测失败,请重试。",
    "game.err.claimFailed": "领取失败,请重试。",
    "game.err.cannotRestore": "暂时无法恢复本局,请稍等或返回首页。",
    "game.err.gameError": "对局错误",
    "game.err.notInGame": "你不在本局中",
  },
};

const LangContext = createContext({ lang: "en", setLang: () => {}, t: (k) => k });

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    if (typeof window === "undefined") return "en";
    const v = window.localStorage.getItem(LANG_KEY);
    return v === "zh" || v === "en" ? v : "en";
  });

  useEffect(() => {
    if (typeof document !== "undefined") document.documentElement.lang = lang;
    if (typeof window !== "undefined") window.localStorage.setItem(LANG_KEY, lang);
  }, [lang]);

  const setLang = useCallback((code) => {
    if (code === "en" || code === "zh") setLangState(code);
  }, []);

  const t = useCallback(
    (key, vars) => {
      const d = DICT[lang] || DICT.en;
      const raw = d[key] ?? DICT.en[key] ?? key;
      if (!vars) return raw;
      return raw.replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : `{${k}}`));
    },
    [lang]
  );

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}

export function useT() {
  return useContext(LangContext).t;
}
